# Generated by Django 2.1.5 on 2019-02-20 08:49

from django.db import migrations, models
import django.db.models.deletion
import gameplay.models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0003_auto_20190220_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='by_first_player',
            field=models.BooleanField(editable=False, verbose_name=gameplay.models.Game),
        ),
        migrations.AlterField(
            model_name='move',
            name='game',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='gameplay.Game'),
        ),
    ]
